config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :favourite
    end
  end
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
   validates :posts, presence: true
   validates :image, presence: true
   belongs_to :user
   has_many :favorites, dependent: :destroy
   has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
 validates :email, presence: true, uniqueness: true, length: {maximum: 255},
                   format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
 before_validation {email.downcase!}
 has_secure_password

 validates :password, presence: true, length: {minimum: 6}
 has_many :posts
 has_many :favorites, dependent: :destroy
 has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 include SessionsHelper

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_url, notice: "#you have liked #{favorite.post.user.name}'s post"
  end

  def destroy
    favorite = current_user.favorites.destroy.(post_id: params[:post_id])
    redirect_to @post, notice: "#you have deleted like for #{favorite.post.user.name}'s post"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

 def index
   @posts = Post.all
 end

 def show
   @favorite = current_user.favorites.find_by(post_id: @post.id)
 end

 def new
   if params[:back]
     @post = Post.new(post_params)
   else
     @post = Post.new
   end
 end

 def edit
   @post = Post.find(params[:id])
 end

 def create
   @post = current_user.posts.build(post_params)
   if params[:back]
     render :new
   else
     @post.save
     PostMailer.post_mail(@post).deliver
     flash[:notice] = 'post created'
     redirect_to posts_path
   end
 end

 def update
   respond_to do |format|
     if @post.update(post_params)
       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
       format.json { render :show, status: :ok, location: @post }
     else
       format.html { render :edit }
       format.json { render json: @post.errors, status: :unprocessable_entity }
     end
   end
 end

 def confirm
   @post = Post.new(post_params)
   @post.user_id = current_user.id
 end

 def destroy
   @post.destroy
   respond_to do |format|
     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private
 def set_post
   @post = Post.find(params[:id])
 end

 def post_params
   params.require(:post).permit(:image, :image_cache, :user_id, :name, :email, :posts)
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   if logged_in?
     redirect_to posts_path
   end
 end

 def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     flash[:notice] = 'login successful'
     redirect_to posts_path
   else
     flash[:danger] = 'failed to login'
     render :new
   end
 end

 def destroy
   session.delete(:user_id)
   flash[:notice ]= 'logged out'
   redirect_to new_session_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order(created_at: "DESC")
  end

  def new
    @user = User.new
    if logged_in?
      redirect_to posts_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: 'User was successfully created'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), success: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def favourite
    @user = User.find(params[:id])
    @favorites = current_user.favorite_posts.all
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to new_user_path, notice: 'User was successfully destroyed.'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || "create"
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram clone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <%= csrf_meta_tags %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <body>
    <header class="container">

        <% if logged_in? %>
          <ul>
            <li><button type="button" class="btn btn-default"><%= link_to "My profile", user_path(current_user.id) %></li>
            <li><button type="button" class="btn btn-primary"><%= link_to "New Post", new_post_path %></li>
            <li><button type="button" class="btn btn-default"><%= link_to "Favorite", favourite_user_path(current_user.id) %></li>
            <li><button type="button" class="btn btn-danger"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          </ul>
          <% else %>
          <ul>
            <li><button type="button" class="btn btn-default"><%= link_to "Login", new_session_path %></li>
          
          </ul>
      <% end %>
    </header>
    <% flash.each do |key, value| %>

      <%= content_tag(:div, value, class: "#{key}") %>

    <% end %>

    <%= yield %>

    <footer>
      <p>© 2020 Copyright Facebook_clone </p>
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit ) do |form| %>
  <% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :posts %>
    <%= form.text_area :posts %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
  <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>
  <%= form.hidden_field :posts %>
  <p><%= @post.posts %></p>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Share" %>
<% end %>

<%= form_with(model: @post, url: new_post_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :posts %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "back", name:'back' %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<%= link_to 'New Post', new_post_path %>

<% @posts.each do |post| %>
<article class="post">
<% if logged_in? %>
  <button type="button" class="btn btn-default"><%= link_to 'Show', post %>


  <% end %>
  <small><strong><%= post.user.name %></strong></small>
  <% if post.image && post.image.url %>
    <%= image_tag post.image.url(), class: "image" %>
  <% end %>
  <br>
  <large><%= post.posts %></large>
  <br>
  <small><%= post.created_at.strftime('%Y/%-m/%-d %-H:%-M') %></small>
  <% end %>
  </article>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= @post.user.name %>
</p>
<p><strong>Image:</strong>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
</p>

<p><%= @post.posts %></p>

<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <button type="button" class="btn btn-danger"><%= link_to 'Unfavorite', favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <button type="button" class="btn btn-primary"><%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post %>
  <% end %>
<% end %>

<% if @post.user_id == current_user.id %>
  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_post_path(@post) %>
  <button type="button" class="btn btn-danger"><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<button type="button" class="btn btn-default"><%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message|%>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
  <% end %>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>

<p><%= form.text_field :name, placeholder: 'name' %></p>
<p><%= form.email_field :email, placeholder: 'email' %></p>
<p><%= form.password_field :password, placeholder: 'password' %></p>
<p><%= form.password_field :password_confirmation, placeholder: 'password_confirmation' %></p>
<div class="setup_form_button">
  <%= form.submit "Update my account" %>
</div>
<%  end %>
<div class = "setup_form setup_form_to_login">
<p>
  <%= link_to "Home", @user %> |
  <%= link_to 'Back', users_path %>
</p>
</div>

app/views/users/favourite.html.erb
<h1><%= @user.name %></h1>
<table>
  <tbody>
    <% @favorites.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= image_tag(post.image.url) %></td>
        <td><%= post.posts %></td>
        <td><%= link_to 'Show', @post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Home', posts_path %>

app/views/users/index.html.erb
<div class="text-center"
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-4 col-xs-push-4 post">
    <h1>All Users</h1>

  <div class="row list_wrapper">
    <% @users.each do |user| %>
      <div class="row list-head">

        <div class="col-xs-10 user-info">
          <h3>
            <strong> <%= link_to "#{user.name}", user_path(user.id) %> </strong>
          </h3>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-xs-12 link">
        <%= link_to posts_path %><h3>Return to Home</h3>
      </div>
    </div>

  </div>
 </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @user.errors.full_messages.each do |message|%>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <br>
  <div class="form-login box text-center">
    <h1>Sign up for Instagram-clone</h1>
    <p>Check out your friend's Pictures</p>
    <%= form_with(model: @user, local: true) do |form|%>
    <p><%= form.text_field :name, placeholder: 'name', class: "log-in-tag" %></p>
    <br>
    <p><%= form.email_field :email, placeholder: 'email', class: "log-in-tag" %></p>
    <br>
    <p><%= form.password_field :password, placeholder: 'password', class: "log-in-tag" %></p>
    <br>
    <p><%= form.password_field :password_confirmation, placeholder: 'password_confirmation', class: "log-in-tag" %></p>
    <br>
    <p><%= form.file_field :icon, placeholder: 'icon', class: "log-in-tag" %></p>

    <%= form.submit "Create my account" , class: "btn btn-primary"  %>
    <p>Already have an account？<%= link_to 'Login', new_session_path %></p>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid text-center">

  <div class="col-xs-8 col-xs-push-2">
    <p id="notice"><%= notice %></p>
  </div>



            <span style="font-size:36px">
              <%= @user.name %><br>
            </span>
            <strong>Email:</strong>
              <%= @user.email %>


          <% if logged_in? %>
              <% if @user == current_user %>
                <%= link_to 'New Post', new_post_path , class: "btn btn-outline-dark common-btn edit-profile-btn" %>
                <%= link_to 'Edit Info', edit_user_path(@user) , class: "btn btn-outline-dark common-btn edit-profile-btn" %>
                <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger "%>
              <% end %>
          <% end %>

</div>